### ISSUE TITLE
Azure Africa

### ISSUE THREAD

**Issue by JohanGrove** [blrchen/AzureSpeed#70]
When will South Africa data centers be available to test latency etc?

**Comment by unlaudable** [comment]
I've created a PR. #71

**Comment by blrchen** [comment]
South Africa North is added.  South Africa West does not show up in region list in azure portal, I can not add it, latency test requires a storage account created in the target region.

**Comment by blrchen** [comment]
I am closing this now, if anyone knows how to access to South Africa West region, please feel free to re-open

**Comment by JohanGrove** [comment]
Thanks

**Comment by unlaudable** [comment]
Thank you.

As it turns out, the South African West region is setup as a backup for the North.
You need to request special access to use South Africa West.

Explained here... https://azure.microsoft.com/en-us/global-infrastructure/geographies/

"South Africa North: All
South Africa West: Reserved for South Africa North customers requiring in-country disaster recovery"

Thanks again!

**Comment by blrchen** [comment]
@unlaudable Thanks for your research! It seems there is nothing I can do now as South Africa West: is reserved for limited Azure customers.

I will add South Africa West when it's public to all Azure customers.

**Comment by mwolfaardt** [comment]
Seems the spelling of South Africa is incorrect, please fix
